let durak = [
    {name: "Ace of spades"},
    {name: "King of hearts"},
    {name: "Another one"},
    {name: "Another one"},
    {name: "Another one"},
    {name: "Another one"},
    {name: "Another one"},
    {name: "Another one"},
    {name: "Another one"},
    {name: "Another one"},
    {name: "Another one"},
    {name: "Another one"},
    {name: "Another one"},
    {name: "Another one"},
    {name: "Another one"},
    {name: "Another one"},
    {name: "Another one"},
    {name: "Another one"},
    {name: "Another one"},
    {name: "Another one"},
    {name: "Another one"},
    {name: "Another one"},
    {name: "Another one"},
    {name: "Another one"},
    {name: "Another one"},
    {name: "Another one"},
    {name: "Another one"},
    {name: "Another one"},
    {name: "Another one"},
    {name: "Another one"},
    {name: "Another one"},
    {name: "Another one"},
    {name: "Another one"},
    {name: "Another one"},
    {name: "Another one"},
    {name: "Another one"},
];

module.exports = durak;